apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-app
  namespace: vaibhav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-app
  template:
    metadata:
      labels:
        app: mail-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mail
        image: vaibhavkuma779/flaskappcapstone:latest
        imagePullPolicy: Always
        env:
          - name: MONGODB_TABLE
            value: "FLASK"
          - name: MONGODB_HOST
            value: "mongodb-0.mongodb"
          - name: MONGODB_PORT
            value: "27017"
