apiVersion: v1
kind: Service
metadata:
  name: mail-app-svc
  namespace: vaibhav
  labels: 
    name: myapp
spec:
  type: NodePort
  selector:
    app: mail-app
    db: mongodb
  ports:
  - port: 1234
    targetPort: 5050
    nodePort: 32000
